CREATE TABLE Manager(
	id INT NOT NULL IDENTITY(0,1),
	name VARCHAR(30) NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE Client(
	id INT NOT NULL IDENTITY(0,1),
	name VARCHAR(30) NOT NULL,
	status VARCHAR(15) NOT NULL,
	manager VARCHAR(30) NOT NULL,
	buyedProduct INT NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE Product(
	id INT NOT NULL IDENTITY(0,1),
	name VARCHAR(30) NOT NULL,
	type VARCHAR(8) NOT NULL,
	period VARCHAR(7) NOT NULL,
	PRIMARY KEY(id)
);
